### ISSUE TITLE
YAML Zerocode Implementation

### ISSUE THREAD

**Issue by vkjha2000** [authorjapps/zerocode#277]
Implement YAML driven tests.

GIVEN a YAML dsl test case to test an API

WHEN I execute the test using a JUnit Runner

THEN I shall be able to get the response of the API validated

AC2:
TODO- Update README and Create Wiki pages for this  too.

### Details

The YAML equivalent of the below Scenario Spec
```javaScript
{
    "scenarioName": "As simple GET request response",
    "steps": [
        {
            "name": "find_match",
            "url": "/api/v1/search/persons",
            "operation": "GET",
            "request": {
                "queryParams": {
                    "lang": "Amazing",
                    "city": "Lon"
                }
            },
            "verifications": {
                "status": 200,
                "body": {
                    "exactMatches": true,
                    "name": "Mr Bean",
                    "city": "Lon"
                }
            }
        }
    ]
}
```

is below.

```yaml
---
scenarioName: As simple GET request response
steps:
- name: find_match
  url: "/api/v1/search/persons"
  operation: GET
  request:
    queryParams:
      lang: Amazing
      city: Lon
  verifications:
    status: 200
    body:
      exactMatches: true
      name: Mr Bean
      city: Lon
```

or below.
Note- The optional double quotes for String fields.
```yaml
---
scenarioName: As simple GET request response
steps:
- name: "find_match"
  url: "/api/v1/search/persons"
  operation: "GET"
  request:
    queryParams:
      lang: "Amazing"
      city: "Lon"
  verifications:
    status: 200
    body:
      exactMatches: true
      name: "Mr Bean"
      city: "Lon"
```

To run the above `Scenario`, please point to the YAML file and run via JUnit. 

```java
public class MyApiScenarioTest{

    @Test
    @Scenario("integration_test_files/yaml/simple_get_api_test.yml")
    public void testSimpleGetApi_yaml() throws Exception {
    }

}
```

**Comment by nirmalchandra** [comment]
Updated the description.

Also the YAML with an array example is below.
```yaml
---
scenarioName: A simple GET API Scenario
steps:
- name: "find_match"
  url: "/api/v1/persons/p001"
  operation: "GET"
  request:
    headers:
      x-api-key: "Ama-zing-key"
      x-api-secret: "Sec-ret-stuff"
  verifications:
    status: 200
    body:
      exactMatches: true
      name: "Mr Bean"
      addresses:
      - type: "office"
        line1: "10 Random St"
      - type: "home"
        line1: "300 Random St"
```

where `addresses` is an array containing two elements.

**Comment by nirmalchandra** [comment]
Wiki Page:
https://github.com/authorjapps/zerocode/wiki/YAML-DSL-For-Test-Scenarios

**Comment by authorjapps** [comment]
Available in `version 1.3.13`

**Comment by authorjapps** [comment]
@vkjha2000 , fyi only. Wiki page for YAML DSL updated!

**Comment by vkjha2000** [comment]
Can you please support both `method` also which is equivalent to `operation`?

**Comment by authorjapps** [comment]
Sounds ok. 
Available in version `1.3.14`

**Comment by siddhagalaxy** [comment]
Just checking, if you support `validators` ? Is there any help somewhere in readme or wiki?
I am looking for something like below:
```yaml
---
scenarioName: As simple GET scenario...
steps:
- name: find_match
  url: "/api/v1/search/persons"
  method: GET
  request:
    queryParams:
      city: Lon
  validators:
  - field: "$.status"
     value: 200
  - field: "$.body.name"
     value: Mr Bean
```

Basically I should be able to point to any field using a JSON Path and validate that field. In this case I do not have to go via the hassles of STRICT and LINIENT matching...?
```
  validators:
  - field: "$.status"
     value: 200
  - field: "$.body.name"
     value: Mr Bean
  - field: "$.body.x.y.pointer.to.a.field"
     value: Expected value of that field
```

fyi, [pyresttest](https://github.com/svanoort/pyresttest) has some kind of validators as a suggestion... to look at
