### ISSUE TITLE
[TECH-DEBT] validators  in zerocode

### ISSUE THREAD

**Issue by vkjha2000** [authorjapps/zerocode#353]
From: @siddhagalaxy  [#277](https://github.com/authorjapps/zerocode/issues/277#issuecomment-570547597)

Just checking, if you support `validators` already? Is there any help somewhere in readme or wiki?
I am looking for something like below:
```yaml
---
scenarioName: As simple GET scenario...
steps:
- name: find_match
  url: "/api/v1/search/persons"
  method: GET
  request:
    queryParams:
      city: Lon
  validators:
  - field: "$.status"
     value: 200
  - field: "$.body.name"
     value: Mr Bean
```

Basically I should be able to point to any field using a JSON Path and validate that field. In this case I do not have to go via the hassles of STRICT and LINIENT matching...?
```
  validators:
  - field: "$.status"
     value: 200
  - field: "$.body.name"
     value: Mr Bean
  - field: "$.body.x.y.pointer.to.a.field"
     value: Expected value of that field
```

fyi, [pyresttest](https://github.com/svanoort/pyresttest) has some kind of validators as a suggestion... to look at

Benefits
===
One can directly validate a field/path holds a correct value using a flat JSON Path, rather than creating JSON object hirerchy/structure.

ACs
===

AC1:
- Implement the feature

AC2:
- Update Wiki/Readme
