### ISSUE TITLE
Assertion doesn'T support dot (.) properly and make it a jsonPath

### ISSUE THREAD

**Issue by ikus060** [authorjapps/zerocode#481]
Not sure if it's a feature or a bug, but I find it not user friendly.

With the following step:
```
  - name: When consuming output topic, Then the topic contains a json payload.
    url: "kafka-topic:test"
    operation: "consume"
    request:
      consumerLocalConfigs:
        recordType: "JSON"
        commitSync: true
    assertions:
      records:
        - key: "$IS.NOTNULL"
          value:
            '@timestamp': "$IS.NOTNULL"
            '@version': '1'
            host: "$IS.NOTNULL"
            message: "$IS.NOTNULL"
            "SNMPv2-MIB::snmpTrapOID.0": "IF-MIB::linkDown"
            "IF-MIB::ifIndex.1073741824": "1073741824"
            "IF-MIB::ifAdminStatus.1073741824": "3"
            "IF-MIB::ifOperStatus.1073741824": "7"
      size: 1
```
My assertion record contains fields with dot (.) It seams to confuse the assertion processor because the resulting json path become: `$.records[0].value.SNMPv2-MIB::snmpTrapOID.0`

I would expect zerocode to properly escape the field name on it own so the json path would be:
`$.records[0].value.['SNMPv2-MIB::snmpTrapOID.0']`
