### ISSUE TITLE
Does ZeroCode allow non-string values derived from earlier steps to be sent in an array in a request body?

### ISSUE THREAD

**Issue by chemckenna** [authorjapps/zerocode#568]
Hello.

I'm having difficulty inserting and sending an integer in an array as part of a request body.

Where I hardcode a number using JSON:

```
      body: {
        "user_identifiers": [ 1000330999 ]
      }
```

or YAML:

```
      body:
        user_identifiers:
          - 1000330999
```

I get the expected payload, outcome and result when the request is made:

```
  "body" : {
    "user_identifiers" : [ 1000330999 ]
  }
```
However, when I send in an integer derived from an earlier step - I have tried using a response code to guarantee it is not a string - `${$.earlier_step.response.status}`- other integers and the response from a custom function to convert a string number to an integer, it always comes through as:

```
  "body" : {
    "user_identifiers" : [ "10000" ]
  }
```

Is this something that can be worked around, or am I doing something wrong? The API I am using requires integers only.

Thanks.

**Comment by authorjapps** [comment]
Hello @chemckenna , Can you put the entire Scenario file or content here to have a look?

Is it possible to push the JSON scenario to a github repo ?

or

Do a fork of this repo and create a branch, then push this scenario to a Kafka integration-testing module `"kafka-testing"` ?
> "kafka-testing/src/test/resources/kafka/more"

**Comment by chemckenna** [comment]
Hi @authorjapps - thanks for getting back to me.

Is this useful?

```
---
scenarioName: GIVEN- the /usermgmt/v1/user endpoint, WHEN- I invoke POST requests to create users and user groups,
  THEN- I will receive a 200 / 201 responses and add the user to a user group.
ignoreStepFailures: true
steps:
  # Use Stepfile to complete Authorisation.
  - stepFile: "${JSON.FILE:reusable_content/stepfiles/get_authorisation.json}"

  - name: create_user
    url: "${restful.authentication.endpoint.host}/usermgmt/v1/user"
    method: POST
    request:
      headers:
        Authorization: "${token_response}"
      body:
        username: add_user_to_user_group_user
        internal_user: false
        displayName: add_user_to_user_group user
        authenticator: default
        user_roles:
          - User
    verify:
      status: 201
      body:
        uid: "$NOT.NULL"
        message: "success"

  - name: check_user_details
    url: "${restful.authentication.endpoint.host}/usermgmt/v1/user/add_user_to_user_group_user"
    method: GET
    request:
      headers:
        Authorization: "${token_response}"
      body:
        username: add_user_to_user_group_user
        internal_user: false
        displayName: add_user_to_user_group user
        authenticator: default
        user_roles:
          - User
    verify:
      status: 200
      body:
        uid: ${$.create_user.response.body.uid}
        username: add_user_to_user_group_user
        user_roles:
          - user_role
        role: User

  - name: create_user_group
    url: "${restful.authentication.endpoint.host}/usermgmt/v2/groups"
    method: POST
    request:
      headers:
        Authorization: "${token_response}"
      body:
        name: add_user_to_user_group_group
        description: add_user_to_user_group group
        account_id: 1
        role_identifiers:
          - admin
    verify:
      status: 201
      body:
        group_id: "$NOT.NULL"
        name: add_user_to_user_group_group
        description: add_user_to_user_group group
        created_by: admin
        message: Created

  - name: add_user_to_user_group_step
    url: "${restful.authentication.endpoint.host}/usermgmt/v2/groups/${$.create_user_group.response.body.group_id}/members"
    method: POST
    request:
      headers:
        Authorization: "${token_response}"
        Content-Type: application/json
      body:
        user_identifiers:
          - ${$.create_user.response.status}
    verify:
      status: 200
      body:
        group_id: ${$.create_user_group.response.body.group_id}
        message: success
```

where I end up sending the following payload for test step **_add_user_to_user_group_step_**:


```
"body" : {
    "user_identifiers" : [ "201" ]
  }
```

If I use some custom code where I know I return an integer, I also see the array entry as a string.

```
  - name: convertStringToInteger
    url: abc.xyz.abc.convertstringtoint.ConvertStringToInt
    method: convertToInt
    request: "${$.create_user.response.body.uid}"
    verify: "$NOT.NULL"
```

and replace `${$.create_user.response.status}` with `${$.convertStringToInteger.response}` in test step **_add_user_to_user_group_step_**, I get:

```
  "body" : {
    "user_identifiers" : [ "1000330999" ]
  }
```

Thanks.
