### ISSUE TITLE
Loop on step level

### ISSUE THREAD

**Issue by infoShare** [authorjapps/zerocode#606]
Hello,
is there any plan to make "loop" work on a Step level ?
It is working on scenario but even if field exists for the particular step in the model - functionality is not implemented.

Scenario level (working):
```
scenarioName: Example test
loop: 10
steps:
  - name: example_step
    url: infoshare.TestUtil
    operation: sum
    request:
      a: 1
      b: 2
    verify: 3
```

Step level (not working)
```
scenarioName: Example test
steps:
  - name: example_step
    url: infoshare.TestUtil
    loop: 10
    operation: sum
    request:
      a: 1
      b: 2
    verify: 3
```
